# Generated by Django 3.2.4 on 2021-07-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210630_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movielens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('movie_id', models.BigIntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
